name       : rapidjson
version    : 1.1.0
release    : 1
source     :
    - https://github.com/miloyip/rapidjson/archive/v1.1.0.tar.gz : bf7ced29704a1e696fbccf2a2b4ea068e7774fa37f6d7dd4039d0787f8bed98e
license    :
    - BSD
    - JSON
    - MIT
component  : programming.library
summary    : RapidJSON is a C++ library for parsing and generating JSON
description: |
    RapidJSON is a C++ library for parsing and generating JSON. It supports both SOX and DOM style API.
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
